name: update-files

on:
  schedule:
    - cron: "*/10 * * * *"

permissions: read-all

jobs:
  update-files:
    permissions:
      contents: write
      pull-requests: write
    uses: boldlink/terraform-module-support/.github/workflows/update.yaml@feature/auto-merge
    secrets:
      AUTOMATION_TOKEN: ${{ secrets.AUTOMATION_TOKEN }}
      SLACK_WEBHOOK : ${{secrets.SLACK_WEBHOOK}}
